name: Build C++ File

on:
  workflow_dispatch: 
  push:
    branches: [ "main", "dev_branch" ]
  pull_request:
    branches: [ "main", "dev_branch"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt update && sudo apt install -y g++

      - name: Compile hello.cpp
        run: g++ -std=c++17 -O2 -Wall -Wextra hello.cpp -o main

      - name: Run executable
        run: ./main
